<a href="https://colab.research.google.com/github/nicknaks/kis/blob/main/%D0%9D%D0%B0%D0%BA%D0%B0%D0%B7%D0%BD%D0%BE%D0%B8%CC%86_%D0%9D_%D0%90_%D0%9B%D0%B0%D0%B1_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Задание 1
Variant<-16
set.seed(Variant) 
X1<-sample(c(1:20),5)
X2<-sample(c(3:100),5)
X3<-sample(c(0:40),5)
pp1<-runif(5)
p1<-pp1/sum(pp1)
pp2<-runif(5)
p2<-pp2/sum(pp2)
pp3<-runif(5)
p3<-pp3/sum(pp3)

In [ ]:
View(data.frame(X1, X2, X3, p1, p2, p3))

X1 X2 X3 p1         p2        p3        
1  1 96 16 0.29609135 0.2397487 0.12065678
2 15 48  2 0.30313183 0.1984502 0.36343173
3 11 93 37 0.23801734 0.2467172 0.35757481
4  8 86 18 0.14777439 0.1885358 0.13791732
5  4 66 20 0.01498509 0.1265481 0.02041935

In [ ]:
# Теоретический способ
# Мат ожидание
M_X1<-sum(p1*X1) 
M_X2<-sum(p2*X2)
M_X3<-sum(p3*X3)
M_X<-M_X1+M_X2+M_X3

In [ ]:
# Дисперсия
D_X1<-sum(p1*(X1-M_X1)^2)
D_X2<-sum(p2*(X2-M_X2)^2)
D_X3<-sum(p3*(X3-M_X3)^2)
D_X<-D_X1+D_X2+D_X3


In [ ]:
# Ср. квадратичное отклонение
Q=sqrt(D_X)

In [ ]:
# Коэфф. вариации случайной величины
K=(Q/M_X)*100

In [ ]:
# Экспериментальный способ
getRes<-function(X,P){
  y<-runif(1) # случайные числа от 0 до 1
  sum<-0
  res<-0
  for(i in 1:length(P))
    {
    sum<-sum+P[i]
    if(y<=sum)
      {
      res<-X[i]
      break
      }
    }
  return(res)
}

experimental<-c()
for( i in 1:1000){
  experimental<-c(experimental,getRes(X1,p1)+getRes(X2,p2)+getRes(X3,p3))
}
# Мат ожидание
M_exp<-mean(experimental) 
# Ср. квадратич. отклонение
sr_exp<-sd(experimental)
# Дисперсия
D_exp<-sr_exp^2 
# Коэфф. вариации случайной величины
K_exp<-(sr_exp/M_exp)*100

In [ ]:
install.packages("polynom")
library(polynom)

Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)



In [10]:
# Способ с использованием производящей функции
#expand((0.296*z^1+0.303*z^15+0.238*z11+0.148*z^8+0.01*z^4)*(0.239*z^96+0.198*z^48+0.246*z^93+0.188*z^86+0.014*z^66)*(0.120*z^16+0.363*z^2+0.357*z^37+0.137*z^18+0.0204*z^20)

generate_poly <- function(X, P) {
  res <- sample(0, max(X), replace=TRUE)
  for (i in 1:(length(X) + 1)) {
    res[X[i] + 1] <- P[i]
  }
  return(res)
}
gf <- polynomial(coef = generate_poly(X1, p1)) * polynomial(coef = generate_poly(X2, p2)) *
  polynomial(coef = generate_poly(X3, p3))

# используем свойства из определения производящей функции

# Мат. ожидание (путем взятия  первой производной от точки 1)
M <- as.function(deriv(gf))(1)
# Дисперсия (путем взятия второй производной)
D <- as.function(deriv(deriv(gf)))(1) + M - M^2 
# Ср. квадратич.
sr <- sqrt(D) 
# Коэфф. вариации случайной величины, умноженный на 100%
k <- (sr / M)*100 # коэффициент вариации случайной величины + умножаем на 100%

# Cравним результаты

way_1<-c(M_X,D_X,Q,K)
way_2<-c(M_exp,D_exp,sr_exp,K_exp)
way_3<-c(M,D,sr,k)

new_matrix<-rbind(way_1,way_2,way_3)
new_matrix


[,1]     [,2]     [,3]     [,4]    
way_1 107.5344 591.2022 24.31465 22.61105
way_2 108.1500 572.1116 23.91885 22.11637
way_3 107.5344 591.2022 24.31465 22.61105

In [11]:
# Полученные значения практически не отличаются

In [12]:
# Задание 2
Variant<-16
set.seed(Variant) 
# a=lambda*tau == теоретическое мат.ожидание и дисперсия, т.к. дисперсия случайной величины, распределенной по закону Пуассона, равна ее математическому ожиданию
a<-runif(3) 
n<-200000 # произвольное количество

In [13]:
# Способ с использованием производящей функцию для случайной величины, которая распределена по закону Пуассона
#Функция rpois из пакета stats генерит случайные числа, распределенные по закону Пуассона с параметром a=lambda*tau

library(stats)
X1<-rpois(n,a[1])
X2<-rpois(n,a[2])
X3<-rpois(n,a[3])
X<-X1+X2+X3

# Теоретическое мат.ожидание и дисперсия распр. по закону Пуассона
M_2<-a[1]+a[2]+a[3] 
D_2<-a[1]+a[2]+a[3]
# Ср. квадратич.
sr_2<-sqrt(D_2)
k_2<-(sr_2/M_2)*100

In [14]:
# Другой способ
M_py<-mean(X)
# Ср. квадратич.
sr_py<-sd(X)
# Дисперсия
D_py<-sr_py^2 
K_py<-(sr_py/M_py)*100


# Выведем результаты
way_1<-c(M_2,D_2,sr_2,k_2)
way_2<-c(M_py,D_py,sr_py,K_py)

new_matrix1<-rbind(way_1,way_2)
new_matrix1


[,1]     [,2]     [,3]     [,4]    
way_1 1.377339 1.377339 1.173601 85.20785
way_2 1.371020 1.369761 1.170368 85.36476

In [ ]:
# Полученные значения практически не отличаются

In [15]:
# Задание 3 

Variant<-16
set.seed(Variant) 
lambda<-runif(7)[7]
T<-1/lambda

# закон распределения случайной величины (СВ), 
# распределенной по экспоненциальному закону
# F(t) = P(тау<t) = 1 - e^(-lambda*t)

# плотность вероятности F(t)
# f(t) = F'(t) = lambda*e^(-lambda*t)

# переход от действительной переменной к комплексной
# Bi(s) = integral(0,inf) [e^-st] dF(t) 
#      = integral(0,inf) [(e^-st) * f(t)] dt
#      = integral(0,inf) [(e^-st) * lambda*e^(-lambda*t)]dt <- это вводим в вольфрам
#      = lambda/(lambda+s)

# мат.ожидание 
# M(тау) = -B'(s) |s=0
#        = -(lambda/(lambda+s))'
#        = -(-lambda/((lambda+s)^2)) | s=0
#        = 1/lambda
M3teor = 1/lambda
# дисперсия
# D(тау) = B''(s) - (B'(s))^2 |s=0
# B''(s) = (lambda/(lambda+s))''
#        = (2*lambda) / (lambda + s)^3 |s=0
#        = 2/*lambda^2
# D(тау) = 2/*lambda^2 - (-1/lambda)^2
#        = 1/*lambda^2
D3teor = 1/(lambda^2)
# среднее квадратичное
SD3teor <- sqrt(D3teor)
# коэфициент вариации
COV3teor <- (SD3teor/M3teor)*100

# экспериментально
n <- 10000
exp3<-rexp(n,lambda) 
M3exp = mean(exp3)
SD3exp = sd(exp3)
D3exp <- SD3exp^2
COV3exp <- (SD3exp/M3exp)*100

# для k программ
# если непрерывная случайная величина тау определяется, как сумма случайных величин
# значит преобразование Лапласа-Стилтьеса (Л-С) для СВ тау равно произведению 
# преобразований Л-С для каждой величин тау_1 + ... + тау_k
# тау =  тау_1 + тау_2 + ... + тау_k
# B(s) = B1(s) + B2(s) + ... + Bk(s) = (Bi(s))^k
# B'(s) = ((lambda/(lambda+s))^k)' -> в вольфрам 
#       = - k * lambda^k * (s+lambda)^(-k-1) |s=0
#       = - k * lambda^k * lambda^(-k-1)
#       = - k / lambda
# B''(s) = ((lambda/(lambda+s))^k)''
#        = - k * (-k-1) * lambda^k * (s+lambda)^(-k-2) |s=0
#        = (k^2+k) * lambda^k * lambda^(-k-2)
#        = (k^2+k) / lambda^2
# M = -B'(s) = k/lambda
# D = B''(s) - (B'(s))^2 = 
#   = (k^2+k)/lambda^2 - k^2/lambda^2
#   = k/lambda^2
k <- 100 # любой

M3teork = k/lambda
D3teork = k/(lambda^2)
SD3teork <- sqrt(D3teork)
COV3teork <- (SD3teork/M3teork)*100

# экспериментально для k случайных величин
n <- 10000

exp3k<-c()
for (i in c(1:n)) {
  r <- rexp(k,lambda);
  exp3k <- append(exp3k ,sum(r))
}

M3expk = mean(exp3k)
SD3expk = sd(exp3k)
D3expk <- SD3expk^2
COV3expk <- (SD3expk/M3expk)*100

results3 = data.frame(row.names=c("мат.ожидание", "дисперсия", "ср.квадратичное", "коэф.вариации"))
results3['Теоретически'] = c(M3teor, D3teor, SD3teor, COV3teor)
results3['Экспериментально'] = c(M3exp, D3exp, SD3exp, COV3exp)
results3[paste('Экспериментально для k =', k)] = c(M3teork, D3teork, SD3teork, COV3teork)
results3[paste('Теоретически для k =', k)] = c(M3expk, D3expk, SD3expk, COV3expk)

View(results3)

Теоретически Экспериментально Экспериментально для k = 100
мат.ожидание     13.4522      13.51251         1345.220                   
дисперсия       180.9617     182.64936        18096.173                   
ср.квадратичное  13.4522      13.51478          134.522                   
коэф.вариации   100.0000     100.01681           10.000                   
                Теоретически для k = 100
мат.ожидание     1344.67842             
дисперсия       18719.87571             
ср.квадратичное   136.82060             
коэф.вариации      10.17497

In [16]:
# Задание 4 
T <- 1
n <- 1000
sum <- 0
lambda <- 3 # берем любой, для эксперимента

for (i in c(1:n)){
  r<- rpois(1, lambda*T) # случайная величина, распределенная по закону Пуассона
  
  for (j in c(1:r)) {
    r = runif(1)
    if (r <= 1) {
      sum <- sum+1
    }
  }
}

print(sum/n)
print(lambda*T)
# > print(sum/n)
# [1] 3.0835
# > print(lambda*T)
# [1] 3
# числа примерно равны, значит суммарная величина распределена по закону пуассона

results4 = data.frame(row.names=c("мат.ожидание"))
results4['Теоретически'] = c(lambda*T)
results4['Экспериментально'] = c(sum/n)
View(results4)

[1] 3.033
[1] 3


Теоретически Экспериментально
мат.ожидание 3            3.033

In [17]:
# Задание 5


Серверная станция состоит из двух модулей питания. Время безотказной работы каждого из них распределено по показательному закону с одинаковыми параметрами:
\begin{align}
𝑓(𝑡)=𝜆𝑒^{−𝜆𝑡} 
\end{align}
𝑡  - время работы одного модуля до первого отказа. Второй модуль питания включается сразу же после отказа первого. Определить плотность вероятности времени безотказной работы всей системы, а также математическое ожидание и дисперсию времени безотказной работы.

время безотказной работы модуля 1 и 2:
\begin{align}
t1, t2 
\end{align}

время безотказной работы всей системы:
\begin{align}
t = t_1+t_2 
\end{align}

Таким образом, необходимо определить, каково распределение вероятности для случайной величины t.

\begin{align}
F(t_i<T) = 1 - e^{-λt_i}
\end{align}
** Плотность распределения вероятностей **
(Свойство 9)

\begin{align}
  \int_{A(t)}^{B(t)} f(t1)*f(t-t1) dt1
\end{align}

\begin{align}
  f(t1) = λe^{-λt1}
\end{align}

\begin{align}
  f(t2) = λe^{-λ(t-t1)}
\end{align}

Пределы интегрирования A и B вычисляются по формулам:
\begin{align}
  A(t) = a + \frac{(t-(a+d) + |t-(a+d)|)}{2}
\end{align}

\begin{align}
B(t) =  b + \frac{(t-(b+c) - |t-(b+c)|)}{2}
\end{align}

\begin{align}
  a <= t1 <= b, c <= t2 <= d
\end{align}

\begin{align}
  a = c = 0, b = d = inf
\end{align}
Выполним преобразование Лапласа над плотностью вероятности:
\begin{align}
   B_t(s) = \int_{0}^{inf} e^{-st}dF(t) = \int_{0}^{inf} e^{-st}f(t)dt
\end{align}

\begin{align}
   B_t(s) = \int_{0}^{inf} e^{-st}λ^2 e^{(-λt)}t dt
\end{align}

\begin{align}
   B_t(s) = \frac{λ^2}{(λ+s)^2}
\end{align}

** Математическое ожидание **
\begin{align}
   M = -B'_t(s)|_{s=0}
\end{align}

\begin{align}
   M = - \frac{-2λ^2}{(s+λ)^3} |_{s=0} = - \frac{-2}{λ} = \frac{2}{λ}
\end{align}

** Дисперсия **
\begin{align}
   D = B''_t(s)-(B'_t(s))^2|_{s=0}
\end{align}

\begin{align}
   D = \frac{6}{λ^2} - \left(\frac{-2}{λ}\right)^2 = \frac{2}{λ^2}
\end{align}

In [18]:
Variant<-16
alpha<-runif(100)[77]
alpha

[1] 0.8768528

In [19]:
# Теоретический способ
M_5<-2/alpha
D_5<-2/(alpha)^2

In [20]:
# Экспериментальный способ
library(stats)
n<-20000
t1<-c()
for (i in c(1:n)) {
  t<-sum(rexp(2, alpha))
  t1<-c(t1, t)
}

M_exp<-mean(t1)
D_exp<-sd(t1)^2

In [22]:
way_1<-c(M_5,D_5) # теоретическое
way_2<-c(M_exp,D_exp) #экспериментальное

new_matrix5<-rbind(way_1,way_2)
new_matrix5

[,1]     [,2]    
way_1 2.280885 2.601217
way_2 2.304251 2.660954

In [ ]:
# Полученные значения практически не отличаются